### PR TITLE
Fix required number of slots calculation

### LINKED ISSUE #55: Total required slots computation is incorrect
This function computes the total number of required slots
```Go
func (m *Master) countRequiredSlots() int {
	cnt := len(m.scheduledTasks) + len(m.newTasks)
	if cnt > m.maxSlots() {
		return m.maxSlots()
	}
	return cnt
}
```
But we can't simply add `len(m.newTasks)` because not every task can be scheduled because every job can only have `j.maxTask` running.

### PR DESCRIPTION
**Pull request by kc1212**
The PR  also adds `completedJobs` to status page

fixes #55

### CODE REVIEW

**Review by aaronang — APPROVED** [review]

File: lib/master/autoscaler.go [hunk 1]
```diff
@@ -71,7 +71,10 @@ func (m *Master) maxSlots() int {
 }
 
 func (m *Master) countRequiredSlots() int {
-	cnt := len(m.scheduledTasks) + len(m.newTasks)
+	cnt := 0
+	for _, v := range m.jobs {
```
Comment (victor-li) [inline lib/master/autoscaler.go]: I think it is better to rename `v` to `job` or `j` for better readability

Comment (kc1212) [reply lib/master/autoscaler.go]: Updated

**Review by victor-li — APPROVED** [review]
